name: FrontEnd Pipline

on:
    push:
        branches: 
            - main
        
env:
    BOCKER_IMAGE:  ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_REPOSITORY}}
    SERVICE_NAME: ${{ vars.SERVICE_NAME }}
    DOCKER_COMPOSE_PATH: ${{ vars.DOCKER_COMPOSE_PATH}}


jobs:
    Unit-Test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v6
            
            - name: Install Dep
              run: npm i

            - name: run unit Test
              run: npm run test

            

    Build-And-Push:
        runs-on: ubuntu-latest
        needs: Unit-Test
        steps:
            - name: Clone Repo
              uses: actions/checkout@v6

            - name: build docker image
              run: docker build -t ${{ env.BOCKER_IMAGE}} --build-arg VITE_API_URL=https://api.session15.lebondeveloppeur.net .

            - name: Tag docker image
              run: docker tag ${{ env.BOCKER_IMAGE}} ${{ env.BOCKER_IMAGE}}:v${{github.run_number}}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: push image to dockerhub
              run: docker push ${{ env.BOCKER_IMAGE}}:v${{github.run_number}}
                    
                    
            - name: push image to dockerhub
              run: docker push ${{ env.BOCKER_IMAGE}}

    Deployment:
        runs-on: ubuntu-latest
        needs: Build-And-Push
        steps:
            - name: Connect Via SSH and Deploy
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                script: |
                    cd ${{ env.DOCKER_COMPOSE_PATH }}
                    sudo docker compose down ${{env.SERVICE_NAME}}
                    sudo docker compose pull ${{env.SERVICE_NAME}}
                    sudo docker compose up -d --force-recreate ${{env.SERVICE_NAME}}